language: node_js
node_js:
 - 0.12
before_script:
 - npm install
script:
  - npm test
sudo: required
branch: staging
deploy:
 provider: heroku
 app: vantage-backend-staging
 api_key: "06aff914-9c1d-4d4b-b653-eaf5aaddba3a"
 on:
  all_branches: true
  tags: false
