language: node_js
node_js:
 - 0.12
before_script:
 - npm install
script:
  - npm test
sudo: required
branch: staging
deploy:
 provider: heroku
 app: vantage-backend-staging
 api_key: "a554c7f3-d5b7-43a8-ba7d-14997cf716f1"
 branch: staging
